# Generated by Django 4.2 on 2023-04-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='Равна ли С сумме A и B ?', max_length=255, verbose_name='Формулировка задачи')),
                ('a', models.IntegerField(default=0, verbose_name='Значение А')),
                ('b', models.IntegerField(default=0, help_text='Подсказка для поля B', verbose_name='Значение B')),
                ('c', models.FloatField(default=0, verbose_name='Значение С')),
                ('current_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения(save)')),
            ],
            options={
                'verbose_name': 'A_B_C',
                'verbose_name_plural': 'A_B_C_S',
                'ordering': ('-id', '-a'),
            },
        ),
    ]
