# Generated by Django 4.2 on 2023-04-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abc',
            options={'ordering': ('id', '-a'), 'verbose_name': 'A_B_C', 'verbose_name_plural': 'A_B_C_S'},
        ),
    ]
