# Generated by Django 4.2 on 2023-04-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_task', '0002_alter_abc_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='c',
            field=models.IntegerField(default=0, verbose_name='Значение С'),
        ),
    ]
