# Generated by Django 4.2.1 on 2023-06-03 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo_task', '0003_alter_abc_c'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abc',
            options={'ordering': ('-id'), 'verbose_name': 'A_B_C', 'verbose_name_plural': 'A_B_C_S'},
        ),
    ]
