# Generated by Django 4.1.7 on 2023-06-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_task', '0004_alter_abc_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abc',
            options={'ordering': ('-id', 'A'), 'verbose_name': 'A_H_R_M', 'verbose_name_plural': 'A_B_C_S'},
        ),
        migrations.RemoveField(
            model_name='abc',
            name='a',
        ),
        migrations.RemoveField(
            model_name='abc',
            name='b',
        ),
        migrations.RemoveField(
            model_name='abc',
            name='c',
        ),
        migrations.AddField(
            model_name='abc',
            name='H',
            field=models.IntegerField(default=0, help_text='Высота цилиндра', verbose_name='Высота цилиндра'),
        ),
        migrations.AddField(
            model_name='abc',
            name='M',
            field=models.IntegerField(default=0, verbose_name='Объем жидкости'),
        ),
        migrations.AddField(
            model_name='abc',
            name='R',
            field=models.IntegerField(default=0, help_text='Радиус цилиндра', verbose_name='Радиус цилиндра'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='task',
            field=models.CharField(default='1007. Имеются две ёмкости: кубическая с ребром A, цилиндрическая с высотой H и радиусом основания R. Определить, поместится ли жидкость объёма M в первую ёмкость, во вторую, в обе.', max_length=255, verbose_name='Формулировка задачи'),
        ),
        migrations.AddField(
            model_name='abc',
            name='A',
            field=models.IntegerField(default=0, help_text='Ребро куба', verbose_name='Ребро куба'),
        ),
    ]
