# Generated by Django 4.1.7 on 2023-06-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_task', '0005_alter_abc_options_remove_abc_a_remove_abc_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='A',
            field=models.IntegerField(default=0, verbose_name='Ребро куба'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='H',
            field=models.IntegerField(default=0, verbose_name='Высота цилиндра'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='R',
            field=models.IntegerField(default=0, verbose_name='Радиус цилиндра'),
        ),
    ]
