# Generated by Django 4.1.7 on 2023-06-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_task', '0006_alter_abc_a_alter_abc_h_alter_abc_r'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abc',
            options={'ordering': ('-id', 'A'), 'verbose_name': 'A_H_R_M', 'verbose_name_plural': 'A_H_R_M_S'},
        ),
        migrations.AlterField(
            model_name='abc',
            name='A',
            field=models.IntegerField(default=1, verbose_name='Ребро куба'),
        ),
    ]
