# Generated by Django 4.1.7 on 2023-06-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_task', '0008_alter_abc_options_remove_abc_a_remove_abc_h_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abc',
            options={'ordering': ('id', '-A'), 'verbose_name': 'A_H_R_M', 'verbose_name_plural': 'A_B_C_S'},
        ),
        migrations.RenameField(
            model_name='abc',
            old_name='a',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='abc',
            old_name='b',
            new_name='H',
        ),
        migrations.RenameField(
            model_name='abc',
            old_name='c',
            new_name='R',
        ),
        migrations.AddField(
            model_name='abc',
            name='M',
            field=models.IntegerField(default=0, verbose_name='Обьем жидкости'),
        ),
    ]
