# Generated by Django 4.1.7 on 2023-06-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_task', '0009_alter_abc_options_rename_a_abc_a_rename_b_abc_h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='A',
            field=models.IntegerField(default=0, verbose_name='Ребро куба'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='H',
            field=models.IntegerField(default=0, verbose_name='Высота цилиндра'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='R',
            field=models.IntegerField(default=0, verbose_name='Радиус цилиндра'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='task',
            field=models.CharField(default='1007. Имеются две ёмкости: кубическая с ребром A, цилиндрическая с высотой H и радиусом основания R. Определить, поместится ли жидкость объёма M в первую ёмкость, во вторую, в обе.', max_length=255, verbose_name='Формулировка задачи'),
        ),
    ]
