# Generated by Django 4.1.7 on 2023-06-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo_task', '0010_alter_abc_a_alter_abc_h_alter_abc_r_alter_abc_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abc',
            options={'ordering': ('id', 'current_date'), 'verbose_name': 'A_H_R_M', 'verbose_name_plural': 'A_B_C_S'},
        ),
    ]
