# Generated by Django 4.1.7 on 2023-06-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo_task', '0014_alter_abc_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abc',
            new_name='AlgoTask',
        ),
    ]
