# Generated by Django 4.1.7 on 2023-06-06 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=225)),
                ('surname', models.CharField(max_length=225, unique=True)),
            ],
            options={
                'verbose_name': 'instructor',
                'verbose_name_plural': 'instructors',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PriceModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=225)),
                ('number_of_trainings', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
            options={
                'verbose_name': 'price',
                'verbose_name_plural': 'prices',
                'ordering': ('number_of_trainings', 'cost'),
            },
        ),
        migrations.CreateModel(
            name='ReviewModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=5000)),
                ('current_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=225)),
                ('current_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TimetableModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=5)),
                ('time_slot', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=30)),
                ('instructor', models.ForeignKey(db_column='instructor_surname', on_delete=django.db.models.deletion.CASCADE, to='website.instructormodels', to_field='surname')),
            ],
            options={
                'verbose_name': 'timetable',
                'verbose_name_plural': 'timetable',
                'ordering': ('time_slot',),
            },
        ),
        migrations.CreateModel(
            name='InformationOfInstructorModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=225)),
                ('information', models.CharField(max_length=300)),
                ('instructor', models.ForeignKey(db_column='instructor_surname', on_delete=django.db.models.deletion.CASCADE, to='website.instructormodels', to_field='surname')),
            ],
            options={
                'verbose_name': 'information of instructor',
                'verbose_name_plural': 'information of instructors',
                'ordering': ('id',),
            },
        ),
    ]
