# Generated by Django 4.1.7 on 2023-06-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemodels',
            name='cost',
            field=models.IntegerField(verbose_name='sa'),
        ),
        migrations.AlterField(
            model_name='pricemodels',
            name='description',
            field=models.CharField(max_length=225, verbose_name='sasa'),
        ),
        migrations.AlterField(
            model_name='pricemodels',
            name='number_of_trainings',
            field=models.IntegerField(verbose_name='s'),
        ),
    ]
