# Generated by Django 4.1.7 on 2023-06-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_pricemodels_cost_alter_pricemodels_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=225)),
                ('surname', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'instructor',
                'verbose_name_plural': 'instructors',
                'ordering': ('id',),
            },
        ),
    ]
